### ISSUE TITLE
most files, esp. executable ones, have CR+LF line endings

### ISSUE THREAD

**Issue by holgerjakobs** [hpheidinger/vtcl.vtcl-8.6#1]
While the Tcl interpreter may be lenient when it comes to line endings, the exec() of Unix/Linux isn't.

So if the first line of a script with hash-bang notation has a CR as its last character, this character is regarded as the last one of the path to the interpreter. Since there is no executable named '/bin/sh\r', it fails badly.

So, please stick to standards and save _all_ Tcl files with only LF as line separator or - at least! - remove the \r at the end of the first line.

**Comment by hpheidinger** [comment]
You must have picked the stone-old 1.6.1.a1 package from SourceForge ...
Someone of the former maintainers must have used a Windows system to
maintain vTcl ... so all shellscripts got ... errrr ... inflicted by CRLFs ...
Make a 'git clone ...' of the GitHub repository, if you are a daredevil or pick one of the preliminary
packages that I meanwhile provided (see the 'Access link' in the Wiki) and pick your choice.
I already ran 'dos2unix' across all shell scripts and that fixed this DOS'ish CR/LF line terminations.
If you think you found a shellscript that still has CR/LF terminated lines, please name the file.

Best regards, hph
