### ISSUE TITLE
VTcl on Windows/MinGW

### ISSUE THREAD

**Issue by sjpedro** [hpheidinger/vtcl.vtcl-8.6#2]
Issue request forwarded from VTcl @ SourceForge

[support-requests:#35- VTcl on Windows/MinGW](https://sourceforge.net/p/vtcl/support-requests/35/)

Dear Sirs
Attempted to install VisualTcl in a MinGW setting (evertying else required is already there, eg "wish's", tcl/tk etc file). Unfortunately, the config file appears to be "hardwired" for Unix/Linux.
Is there any chance of a config file that would be MinGW "friendly", or at least some instructions on how we might accomplish the install. For example, in our case, all sources are put in a [Build] dir, and typically something along the lines of
cd [Build] && \ ./configure -- prefix=[Dest] ... && \ make && \ make install
is used,
Our MinGW dir structure for installed packages follows:
D:\Apps\MingW\local32\bin
D:\Apps\MingW\local32\lib
... etc
Any assistance with editing the VisualTcl config etc would be greatly appreciated.
Many thanks
DrO

**Comment by hpheidinger** [comment]
I cannot get a clue what you are trying to attempt.

MinGW is a  crutch to run the GCC compiler framework on Windows - it is NEITHER  a substitute for a unixoid runtime environment like 'cygwin' NOR it is a substitute for a UNIX-OS.

## From the MinGW docs ...

"MinGW compilers provide access to the functionality of the Microsoft C runtime and some language-specific runtimes. MinGW, being Minimalist, does not, and never will, attempt to provide a POSIX runtime environment for POSIX application deployment on MS-Windows. If you want POSIX application deployment on this platform, please consider Cygwin instead."

Just get a decent platform and have fun ...
